/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import dao.DateTime;

/**
 *
 * @author 55459
 */
public class TelaInicial extends javax.swing.JFrame {
    private DateTime datetime;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCaixa = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastro.setBackground(new java.awt.Color(57, 209, 57));
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastro");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        btnCaixa.setBackground(new java.awt.Color(57, 209, 57));
        btnCaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnCaixa.setText("Caixa");
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });

        btnPesquisa.setBackground(new java.awt.Color(57, 209, 57));
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setText("Pesquisa");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnEstoque.setBackground(new java.awt.Color(57, 209, 57));
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setText("Estoque");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastro)
                            .addComponent(btnCaixa)
                            .addComponent(btnPesquisa))
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnCaixa)
                        .addGap(37, 37, 37)
                        .addComponent(btnPesquisa)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEstoque)))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
       // Opções que você deseja apresentar
    String[] opcoes = {"Cadastro de Cliente", "Cadastro de fornecedor"
            , "Cadastro de Produto","Cadastro de Funcionario"};
    
    // Mostra o JOptionPane com as opções
    int escolha = JOptionPane.showOptionDialog(
            this, // Componente pai
            "Qual cadastro deseja escolher?", // Mensagem
            "Cadastro", // Título da janela
            JOptionPane.DEFAULT_OPTION, // Tipo de opção
            JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
            null, // Ícone (null usa o ícone padrão)
            opcoes, // Opções disponíveis
            opcoes[0] // Opção padrão
    );

    // Trata a escolha do usuário
    if (escolha == 0) {
        
        CadastroCliente cadastrocliente = new CadastroCliente(); 
        cadastrocliente.setVisible(true); 
        
    } else if (escolha == 1) {
        
        CadastroFornecedor cadastrofornecedor = new CadastroFornecedor(); 
        cadastrofornecedor.setVisible(true); 
    } else if (escolha == 2) {
        
       CadastroProduto cadastroproduto = new CadastroProduto(); 
        cadastroproduto.setVisible(true); 
    }else if (escolha == 3) {
       CadastroFuncionario cadastrofuncionario = new CadastroFuncionario(); 
        cadastrofuncionario.setVisible(true); 
         
    }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        Caixa caixa = new Caixa(); 
        caixa.setVisible(true); 

    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
       Estoque estoque = new Estoque(); 
        estoque.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void customInitComponents() {
        setLayout(new java.awt.BorderLayout()); // Define um layout simples
        datetime = new DateTime();
        add(datetime, java.awt.BorderLayout.CENTER); // Adiciona o DateTime ao centro do painel
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
  




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
